### PR TITLE
feat(ruby-version): set ruby version to 2.5 for all cops

### PR DESCRIPTION
**Pull request by rg-3**

### CODE REVIEW

**Comment by rg-3** [comment]
cc @ayarotsky @urkle

**Comment by rg-3** [comment]
ping @urkle @ayarotsky @raulpopadineti - can you give this one a look? it should be pretty straightforward. unfortunately i can't add reviews to this PR.

**Comment by urkle** [comment]
@rg-3 in the future please request access to the repo vs creating a fork in your GH account.

**Comment by rg-3** [comment]
@urkle Roger that. When can we expect a new release ? I have another PR open this will be useful for.

**Comment by rg-3** [comment]
Ping @urkle

**Comment by rg-3** [comment]
@urkle When can we expect a new release ?

**Pull request merged**
